MOCK_GET_USERS_RESPONSE = [
    {
        "id": 1,
        "first_name": "Pincas",
        "last_name": "De'Vere - Hunt",
        "email": "pdeverehunt0@army.mil",
        "phone": "+1 (859) 586-7994",
        "address_line_1": "0217 American Ash Street",
        "address_line_2": "10th Floor",
        "state": "Kentucky",
        "zip_code": "40586",
        "country": "US",
    },
    {
        "id": 2,
        "first_name": "Gaven",
        "last_name": "Broader",
        "email": "gbroader1@umn.edu",
        "phone": "+1 (303) 670-0267",
        "address_line_1": "41 Homewood Crossing",
        "address_line_2": "PO Box 97288",
        "state": "Colorado",
        "zip_code": "80127",
        "country": "US",
    },
    {
        "id": 3,
        "first_name": "Garrik",
        "last_name": "Mallion",
        "email": "gmallion2@macromedia.com",
        "phone": "+1 (512) 844-2973",
        "address_line_1": "0 Kinsman Point",
        "address_line_2": "PO Box 96736",
        "state": "Texas",
        "zip_code": "78710",
        "country": "US",
    },
    {
        "id": 4,
        "first_name": "Yancey",
        "last_name": "Jinks",
        "email": "yjinks3@example.com",
        "phone": "+1 (316) 321-5261",
        "address_line_1": "9 Kim Lane",
        "address_line_2": "Apt 504",
        "state": "Kansas",
        "zip_code": "67236",
        "country": "US",
    },
    {
        "id": 5,
        "first_name": "Cathee",
        "last_name": "Swindle",
        "email": "cswindle4@unicef.org",
        "phone": "+1 (941) 400-7362",
        "address_line_1": "696 Prairieview Center",
        "address_line_2": "Apt 1924",
        "state": "Florida",
        "zip_code": "34233",
        "country": "US",
    },
    {
        "id": 6,
        "first_name": "Laverne",
        "last_name": "Challender",
        "email": "lchallender5@wired.com",
        "phone": "+1 (571) 756-6871",
        "address_line_1": "6 Judy Trail",
        "address_line_2": "7th Floor",
        "state": "Virginia",
        "zip_code": "20189",
        "country": "US",
    },
    {
        "id": 7,
        "first_name": "Tanitansy",
        "last_name": "Firth",
        "email": "tfirth6@oracle.com",
        "phone": "+1 (239) 712-0431",
        "address_line_1": "133 Nobel Parkway",
        "address_line_2": "PO Box 80093",
        "state": "Florida",
        "zip_code": "33963",
        "country": "US",
    },
    {
        "id": 8,
        "first_name": "Marijo",
        "last_name": "Likely",
        "email": "mlikely7@hibu.com",
        "phone": "+1 (765) 254-0636",
        "address_line_1": "9532 Schurz Way",
        "address_line_2": "PO Box 62000",
        "state": "Indiana",
        "zip_code": "47306",
        "country": "US",
    },
    {
        "id": 9,
        "first_name": "Rowen",
        "last_name": "Gostick",
        "email": "rgostick8@vk.com",
        "phone": "+1 (320) 200-7862",
        "address_line_1": "38 Mcbride Hill",
        "address_line_2": "Suite 81",
        "state": "Minnesota",
        "zip_code": "56398",
        "country": "US",
    },
    {
        "id": 10,
        "first_name": "Barrie",
        "last_name": "Margaret",
        "email": "bmargaret9@github.io",
        "phone": "+1 (816) 528-1650",
        "address_line_1": "31424 Calypso Drive",
        "address_line_2": "PO Box 40083",
        "state": "Kansas",
        "zip_code": "66112",
        "country": "US",
    },
    {
        "id": 11,
        "first_name": "Beatriz",
        "last_name": "Seath",
        "email": "bseatha@mozilla.com",
        "phone": "+1 (917) 497-8003",
        "address_line_1": "0758 Ridgeview Drive",
        "address_line_2": "Suite 2",
        "state": "New York",
        "zip_code": "11215",
        "country": "US",
    },
    {
        "id": 12,
        "first_name": "Carlynn",
        "last_name": "Skinley",
        "email": "cskinleyb@vimeo.com",
        "phone": "+1 (305) 698-2896",
        "address_line_1": "849 Ilene Plaza",
        "address_line_2": "15th Floor",
        "state": "Florida",
        "zip_code": "33261",
        "country": "US",
    },
    {
        "id": 13,
        "first_name": "Lek",
        "last_name": "Bridgestock",
        "email": "lbridgestockc@reference.com",
        "phone": "+1 (816) 253-3955",
        "address_line_1": "827 Hanson Way",
        "address_line_2": "PO Box 51339",
        "state": "Missouri",
        "zip_code": "64109",
        "country": "US",
    },
    {
        "id": 14,
        "first_name": "Aubrey",
        "last_name": "Getcliff",
        "email": "agetcliffd@eepurl.com",
        "phone": "+1 (240) 626-0626",
        "address_line_1": "2 Gina Place",
        "address_line_2": "Suite 92",
        "state": "Maryland",
        "zip_code": "20851",
        "country": "US",
    },
    {
        "id": 15,
        "first_name": "Karylin",
        "last_name": "Minchin",
        "email": "kminchine@mac.com",
        "phone": "+1 (225) 110-8517",
        "address_line_1": "92674 Lighthouse Bay Lane",
        "address_line_2": "PO Box 9733",
        "state": "Louisiana",
        "zip_code": "70826",
        "country": "US",
    },
    {
        "id": 16,
        "first_name": "Nannette",
        "last_name": "Kaesmans",
        "email": "nkaesmansf@g.co",
        "phone": "+1 (917) 989-8035",
        "address_line_1": "50 Carberry Road",
        "address_line_2": "Apt 1851",
        "state": "New York",
        "zip_code": "10034",
        "country": "US",
    },
    {
        "id": 17,
        "first_name": "Kristos",
        "last_name": "Hovey",
        "email": "khoveyg@discuz.net",
        "phone": "+1 (214) 397-9791",
        "address_line_1": "5 Warner Place",
        "address_line_2": "Apt 1146",
        "state": "Texas",
        "zip_code": "75049",
        "country": "US",
    },
    {
        "id": 18,
        "first_name": "Shurwood",
        "last_name": "Beades",
        "email": "sbeadesh@imageshack.us",
        "phone": "+1 (937) 508-1651",
        "address_line_1": "80 Armistice Center",
        "address_line_2": "6th Floor",
        "state": "Ohio",
        "zip_code": "45440",
        "country": "US",
    },
    {
        "id": 19,
        "first_name": "Ulla",
        "last_name": "Rizzardini",
        "email": "urizzardinii@ucla.edu",
        "phone": "+1 (719) 921-7119",
        "address_line_1": "45405 Huxley Center",
        "address_line_2": "Suite 29",
        "state": "Colorado",
        "zip_code": "81010",
        "country": "US",
    },
    {
        "id": 20,
        "first_name": "Dita",
        "last_name": "Frigout",
        "email": "dfrigoutj@multiply.com",
        "phone": "+1 (516) 242-1901",
        "address_line_1": "41321 South Parkway",
        "address_line_2": "14th Floor",
        "state": "New York",
        "zip_code": "11054",
        "country": "US",
    },
]
